version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
